apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  type: NodePort
  selector:
    app: app-server
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: app-server