apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: sample-cluster
spec:
  version: v6.1.0
  pd:
    baseImage: pingcap/pd
    replicas: 2
    requests:
      storage: "500Mi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    replicas: 2
    requests:
      storage: "500Mi"
    config: {}
  tidb:
    baseImage: pingcap/tidb
    replicas: 2
    service:
      # ロードバランサー経由でTiDBにアクセスすることが可能
      type: LoadBalancer
    config: {}